### ISSUE TITLE
NetNode.disconnect raises an TypeError.

### ISSUE THREAD

**Issue by km19809** [QuirkyCort/nethelper#1]
Code: `nethelper.py:448`
```py
def disconnect(self):
        '''
        Disconnect from the server.

        Returns:
            None
        '''
        self._send_req(self.REQ_TYPE_DISCONNECT)
        self.socket.close()
```
`nethelper.py:493`
```py
def _send_req(self, req_type, data):
        data = {
            'type': req_type,
            'data': data
         }
        self._send_frame(self.SERVER_ADDR, self.FRAME_TYPE_REQ, data)
```
Error: `TypeError: _send_req() missing 1 required positional argument: 'data'`

When the `req_type` is `self.REQ_TYPE_DISCONNECT`, `data` is never used. However, current code requires positional argument.
I worked around by assigning 0 to `data`, but I think there is better solution.

**Comment by QuirkyCort** [comment]
Thanks. The data for the disconnect request should be None. I've added it in.

**Comment by km19809** [comment]
Thank you. I was late.

Closing this by 1b357950d9230423e44c8c3d8c3f98920154ab06
